<a href="https://colab.research.google.com/github/DmitriiPushkarev/PythonHomework/blob/main/20_10_%D0%9E%D0%B1%D1%8F%D0%B7%D0%B0%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D0%BE%D0%B5_%D0%B4%D0%B7_%D0%B4%D0%BB%D1%8F_%D0%BE%D0%B1%D0%B5%D0%B8%D1%85_%D0%B3%D1%80%D1%83%D0%BF%D0%BF_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# План:
1. Python
2. Numpy
3. Pandas
4. Regexp + regexp with dataframes
5. Texts
6. Matplotlib, Seaborn
7. Classification, clustering, binary, multiclass, multilabel
8. Metrics
9. Feature extraction
10. Pyspark/sql

<img src="gifs/start.gif" width="400">

# Python

* Целая куча упражнений на типы данных\операторы и функции

https://www.w3resource.com/python-exercises/

Типы данных:
    * Числа (7382, 3.14, 3+4j, Decimal, Fraction)
    * Строки ('net', "your's", u'радость')
    * Списки ([1, [2, 'three'], 4])
    * Словари ({'Alex': 2, 'Brian': 4})
    * Кортежи ('Leo', 21.7, 'single')
    * Множества (set(1,2,3), {'a', 'b', 'c'})
    * Файлы (open('myfile', 'r'))

1. Склеить 3 подстроки "ada", "lovelace", "was considered the world's first computer programmer.". Первые две строки сделать с большой буквы.  (★☆☆)

In [ ]:
a = 'ada'
b = 'lovelca'
c = 'was considered the world''s first computer programmer.'
d = "{} {} {}".format(a.capitalize(), b.capitalize(), c)
print(d)

Ada Lovelca was considered the worlds first computer programmer.


2. Удаление лишних пробельных символов справа, слева, с обоих сторон  (☆☆☆)

In [ ]:
a = ' AMOGUS '
print(a.lstrip())
print(a.rstrip())
print(a.strip())

AMOGUS 
 AMOGUS
AMOGUS


3. Найти первое вхождение в строку подстроки (☆☆☆)

In [ ]:
s1="But if you stick with me, I’m gonna accomplish great things, Morty, and you’re gonna be part of ’em."
s2="you"

##your code
print(s1.find(s2))

7


* isdigit - состоит ли строка из цифр;
* isalpha - состоит ли строка из букв;
* isalnum - состоит ли строка из цифр или букв;
* islower - состоит ли строка из символов в нижнем регистре;
* isupper - состоит ли строка из символов в верхнем регистре;
* istitle - начинаются ли слова в строке с заглавной буквы.

4. Разбить строку по разделителю (☆☆☆)

In [ ]:
s1="Holy#cow,#Rick!#I#didn’t#know#hanging#out#with#you#was#making#me#smarter!"

##your code
a = s1.split('#')
print(a)

['Holy', 'cow,', 'Rick!', 'I', 'didn’t', 'know', 'hanging', 'out', 'with', 'you', 'was', 'making', 'me', 'smarter!']


5. Полученный массив строк склеить через пробел (★☆☆)

In [ ]:
print(' '.join(a))

Holy cow, Rick! I didn’t know hanging out with you was making me smarter!


6. Вывести данные из словаря в три строки в виде "NAME (age AGE) is a JOB" (★☆☆)

(hint: .format())

In [ ]:
personal_data = {1: ("Ann", 29, "Artist"), 
               2: ("Leo", 54, "Programmer"), 
               3: ("Tiffany", 43, "Shop Assistant")}

##your code
print('name {p[0]} age {p[1]} is a job {p[2]}'.format(p = personal_data[1]))
print('name {p[0]} age {p[1]} is a job {p[2]}'.format(p = personal_data[2]))
print('name {p[0]} age {p[1]} is a job {p[2]}'.format(p = personal_data[3]))

name Ann age 29 is a job Artist
name Leo age 54 is a job Programmer
name Tiffany age 43 is a job Shop Assistant


7. Требуется определить, является ли данный год високосным. (год является високосным, если его номер кратен 4, но не кратен 100, а также если он кратен 400.)  (★★☆)

Входные данные: Вводится единственное число - номер года (целое, положительное, не превышает 30000).

Выходные данные: Требуется вывести слово YES, если год является високосным и NO - в противном случае.

In [ ]:
year = int(input("Введите год: "))
if year > 30000 and year < 0:
  print('Неправльное число')
else:
  if (year % 4 == 0 and year % 100 != 0) or year % 400 == 0:
    print('YES')
  else:
    print('NO')

Введите год: 2100
NO


8. Закодируйте каждый элемент списка слов числом, результат сопоставления (слово-число) поместите в словарь.  (★☆☆)

In [ ]:
words = ['Not', 'my', 'cup', 'of', 'tea']

##your code
numbers = [3, 2, 3, 2, 3]
words_dictionary = dict(zip(words, numbers))
print(words_dictionary)

{'Not': 3, 'my': 2, 'cup': 3, 'of': 2, 'tea': 3}


9. Удалить второй элемент из списка по индексу\по значению  (★☆☆)

In [ ]:
dogs = ['border collie', 'australian cattle dog', 'labrador retriever']

##your code
dogs.remove('border collie')
dogs.pop(1)
print(dogs)

['australian cattle dog']


10. Вывести срез списка с 3 по 5 элемент включительно и все слова перевести в верхний регистр (★☆☆)

In [ ]:
dogs = ['border', 'collie', 'australian', 'cattle', 'dog', 'labrador', 'retriever']

##your code
for i in range(5):
    if i > 1:
      print(dogs[i].upper())

AUSTRALIAN
CATTLE
DOG


11. Словарь словарей. Вывести из словаря для каждого питомца его имя, породу, имя владельца, и наличие прививки. Строку вывода формировать через .format() (★☆☆)

In [ ]:
pets = {'willie': {'kind': 'dog', 'owner': 'eric', 'vaccinated': True},
        'walter': {'kind': 'cockroach', 'owner': 'eric', 'vaccinated': False},
        'peso': {'kind': 'dog', 'owner': 'chloe', 'vaccinated': True},
        }

##your code
print('{willie[kind]} {willie[owner]} {willie[vaccinated]}'.format(**pets))
print('{walter[kind]} {walter[owner]} {walter[vaccinated]}'.format(**pets))
print('{peso[kind]} {peso[owner]} {peso[vaccinated]}'.format(**pets))
# я незнаю как компактнее вывести

dog eric True
cockroach eric False
dog chloe True


12. Проверить является ли множество подмножеством другого множества  (★☆☆)

In [ ]:
a=set([2, 5, 6])
b=set([2, 4, 8, 3, 5, 6])

##your code
a.issubset(b)

True

13. Объединить несколько множеств (★☆☆)

In [ ]:
a=set([10, 35, 6, 5])
b=set([2, 4, 8, 3, 5, 6, 35])
c=set([4, 5, 35])

##your code
a.union(b,c)

{2, 3, 4, 5, 6, 8, 10, 35}

14. Посчитать пересечение множества b с остальными из предыдущего задания  (★★☆)

(hint: set.intersection(other, ...) (или set & other &) )

In [ ]:
b.intersection(a,c) 

{5, 35}

15. Вывести множество из элементов, встречающихся в одном множестве, но не встречающиеся в обоих. (★★☆)

(hint: .symmetric_difference())

In [ ]:
a=set([1, 2, 3, 4, 5])
b=set([3, 4, 5, 6, 7])

##your code

In [ ]:
a.symmetric_difference(b)

{1, 2, 6, 7}

16. Предположим, есть файл с данными клиентов. В качестве простого примера воьзьмем txt-файл(нужно создать файл с предложенным/другим содержанием самостоятельно) следующего содержания:

    lastname,age,debt,occupation
    
    Adrianov,25,30000,artist
    
    Нужно считать файл data/credit_sample.txt.
    Сделать словарь вида:
        {lastname: (age,debt,occupation)}
    
    Посчитать сколько уникальных профессий получилось в словаре.
    
    Результат записать в json (★★★)

In [60]:
my_file = open("credit_sample.txt", "w+")


In [ ]:
my_file.write("lastname,age,debt,occupation Adrianov,25,30000,artist!")

In [76]:
import json

In [79]:
my_file = open("credit_sample.txt")
a = my_file.read()
my_file.close()
b = a.split(',')

c = {b[0]:'('+b[1] +','+ b[2] + ',' + b[3] + ')'}
print(c)
jsonStr = json.dumps(c)
print(jsonStr)

{'lastname': '(age,debt,occupation Adrianov)'}
{"lastname": "(age,debt,occupation Adrianov)"}


### os, sys, datetime

In [45]:
from datetime import datetime
from datetime import timedelta
import os, fnmatch

from dateutil.relativedelta import relativedelta

from dateutil.rrule import *

17. Получить список файлов в папке gifs/ и оставить только файлы с расширением .gif (★★☆)

In [47]:
listOfFiles = os.listdir('sample_data') # могла быть папка gifs
pattern = "*.csv" # мог быть формат .gif
for entry in listOfFiles:  
    if fnmatch.fnmatch(entry, pattern):
            print(entry)

california_housing_test.csv
california_housing_train.csv
mnist_train_small.csv
mnist_test.csv


18. Создать папку с названием temp и удалить её (★☆☆)

In [52]:
os.mkdir("temp")
os.rmdir("temp")

19. Вывести переменные среды (★☆☆)

(hint: environ)

In [54]:
os.environ

environ{'NV_LIBCUBLAS_DEV_VERSION': '11.4.1.1043-1',
        'NV_CUDA_COMPAT_PACKAGE': 'cuda-compat-11-2',
        'NV_CUDNN_PACKAGE_DEV': 'libcudnn8-dev=8.1.1.33-1+cuda11.2',
        'LD_LIBRARY_PATH': '/usr/local/nvidia/lib:/usr/local/nvidia/lib64',
        'NV_LIBNCCL_DEV_PACKAGE': 'libnccl-dev=2.8.4-1+cuda11.2',
        'TCLLIBPATH': '/usr/share/tcltk/tcllib1.19',
        'CLOUDSDK_PYTHON': 'python3',
        'LANG': 'en_US.UTF-8',
        'NV_LIBNPP_DEV_PACKAGE': 'libnpp-dev-11-2=11.3.2.152-1',
        'HOSTNAME': 'da779bdd6081',
        'OLDPWD': '/',
        'CLOUDSDK_CONFIG': '/content/.config',
        'NV_LIBNPP_VERSION': '11.3.2.152-1',
        'NV_NVPROF_DEV_PACKAGE': 'cuda-nvprof-11-2=11.2.152-1',
        'NVIDIA_VISIBLE_DEVICES': 'all',
        'NV_NVPROF_VERSION': '11.2.152-1',
        'NV_LIBCUSPARSE_VERSION': '11.4.1.1152-1',
        'DATALAB_SETTINGS_OVERRIDES': '{"kernelManagerProxyPort":6000,"kernelManagerProxyHost":"172.28.0.3","jupyterArgs":["--ip=172.28.0.2"],"de

20. Как игнорировать warrnings?

In [ ]:
# python -W ignore foo.py

* Про datetime и timedelta 

https://www.guru99.com/date-time-and-datetime-classes-in-python.html

21. Вывести сегодняшнюю, вчерашнюю и завтрашнюю дату (☆☆☆)

In [ ]:
print(datetime.now().date())
print(datetime.now().date() - timedelta(days=1))
print(datetime.now().date() + timedelta(days=1))

2022-10-25
2022-10-24
2022-10-26


22. Вывести день недели сегодняшней даты (★☆☆)

In [ ]:
datetime.now().weekday()

1

23. Получить список дат за предыдущую неделю (★★☆)

In [ ]:
d = datetime.now()
print(d + relativedelta(weekday=MO(-1)))
print(d + relativedelta(weekday=TU(-1)))
print(d + relativedelta(weekday=WE(-1)))
print(d + relativedelta(weekday=TH(-1)))
print(d + relativedelta(weekday=FR(-1)))
print(d + relativedelta(weekday=SA(-1)))
print(d + relativedelta(weekday=SU(-1)))

2022-10-24 14:24:43.170232
2022-10-25 14:24:43.170232
2022-10-19 14:24:43.170232
2022-10-20 14:24:43.170232
2022-10-21 14:24:43.170232
2022-10-22 14:24:43.170232
2022-10-23 14:24:43.170232


24. Вывести дату с часами и минутами, отформатировать в формате: 01.12.2019 00:12:54 (★★☆)
            
(hint: now().strftime())

In [ ]:
datetime.now().strftime("%d.%m.%Y, %H:%M:%S")

'25.10.2022, 14:27:05'

25. Исходя из текущей даты вычислить дату предыдущего понедельника (★★★)

In [ ]:
print(d + relativedelta(weekday=MO(-2)))

2022-10-17 14:24:43.170232


# Numpy

### numpy в картинках (реально лучший):

https://jalammar.github.io/visual-numpy/

In [57]:
import numpy as np

1. Задать нулевой вектор размером 10 (★☆☆)

(hint: np.zeros)

In [ ]:
np.zeros(10)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


2. Как найти размер занимаемой памяти любым массивом (★☆☆)

(hint: size, itemsize)

In [ ]:
np.array([1,2,3]).size

3

3. Создать вектор из 10 нулей, кроме пятого элемента, который равен 1 (★☆☆)

In [ ]:
a = np.zeros(10)
a[4] = 1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


4. Создать вектор от 10 до 50 включительно (★☆☆)

(hint:np.arange)

In [ ]:
a = np.arange(10,51)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


5. Перевернуть вектор (первый элемент будет последним) (★☆☆)

In [ ]:
a[::-1]

array([50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34,
       33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17,
       16, 15, 14, 13, 12, 11, 10])

6. Создать матрицу 3х3 с элементами от 0 до 8 (★☆☆)

(hint: reshape)

In [ ]:
a = np.arange(9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


7. Найти индексы не нулевых эемелентов в numpy array [1,2,0,0,4,0] (★☆☆)

(hint: np.nonzero)

In [ ]:
a = np.nonzero([1,2,0,0,4,0])
print(a)

(array([0, 1, 4]),)


8. Создать матрицу 10x10 array с рандомными числами и найти минимум, максимум и среднее (★☆☆)

In [ ]:
a = np.random.random((10,10))
min, max, avg = a.min(), a.max(), a.sum() / a. size
print(min, max, avg)

0.005339188445926513 0.9963869930662308 0.4971286191605418


9. Создать матрицу 8x8 и заполнить 0 и 1 в стиле шахматной доски (★☆☆)

(hint: array[::n])

In [ ]:
a = np.tile(np.array([[0,1],[1,0]]), (4,4))
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


10. Нормализовать рандомную матрицу 5x5 (★☆☆)

(hint: (x - mean) / std)

In [ ]:
a = np.random.random((5,5))
a / (np.sum(a, axis=1)[:, np.newaxis])

array([[0.34847726, 0.1554337 , 0.0991095 , 0.30781565, 0.08916389],
       [0.29547325, 0.22759486, 0.31781994, 0.06324158, 0.09587037],
       [0.18890077, 0.29476431, 0.36921625, 0.13587255, 0.01124612],
       [0.32702448, 0.14058364, 0.23992353, 0.19802391, 0.09444444],
       [0.37799984, 0.12617935, 0.43958414, 0.02877143, 0.02746524]])

11. Найти общие элементы между двумя массивами

(hint: np.intersect1d)

In [ ]:
a1 = np.random.randint(0,10,10)
a2 = np.random.randint(0,10,10)
np.intersect1d(a1,a2)

array([2, 3, 6])

12. Извлечь целую часть рандомного массива чисел различными способами (максимум 5) (★★☆)

In [58]:
a = np.random.randint(0,10,10)
a[0:5]
# я не понял что надо сделать

array([9, 3, 0, 5, 9])

13. Создать рандомный вектор размера 10 и отсортировать его (★★☆)

In [ ]:
a = np.random.random(10)
a.sort()
print(a)

[0.08597771 0.13132446 0.33934351 0.47941373 0.48822208 0.49891765
 0.50228824 0.54864439 0.57474621 0.7952995 ]


14. Проверить одинаковы ли два рандомных массива А и B (★★☆)

(hint: np.allclose, np.array_equal)

In [ ]:
a1 = np.random.random((5,5))
a2 = np.random.random((5,5))
np.array_equal(a1,a2)

False

15. Создать рандомный ветор размером 10 и максимальный элемент заменить на -1 (★★☆)

(hint: argmax)

In [ ]:
a = np.random.random(10)
a[a.argmax()] = -1
print(a)

[ 0.5139871   0.31251177 -1.          0.46909342  0.6917198   0.10371737
  0.87040132  0.14654564  0.55341557  0.86105254]


16. Найдите самый близкий элемент к данному рандомному числу в векторе? (★★☆)

(hint: argmin)

In [ ]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index =  (np.abs(Z-v)).argmin()
print(Z[index])

42


17. Посчитать среднее для каждой строки матрицы (★★☆)

In [ ]:
a = np.arange(18).reshape(3, 6)
np.mean(a, axis = 1)

array([ 2.5,  8.5, 14.5])

18. Посчитать среднее со скользящим окном над массивом (★★★)

(hint: np.cumsum)

In [ ]:
a = np.random.random(10)
np.cumsum(a)

array([0.38041743, 1.16339001, 1.39506149, 2.18597125, 3.02682394,
       3.89682214, 4.05087691, 4.37811721, 4.61001237, 4.95154863])

<img src="gifs/bender.gif" width="400">

# Regular expressions

* Cупер статья на все времена. Особенно понятно все про такие сложные штуки как lookaround. 

https://habr.com/ru/post/349860/


* Задания на регулярки

https://regexone.com/

* На этом сайте удобно тестировать регулярку, которую мучаешь, можно написать несколько примеров и тестировать на них. Важно не забывать выбирать Python:

https://regex101.com/

1. Из строки в файле data/rejson.txt вытащить хэш. Пример:

'master_guid': '<b>233880bb4c50d247f84edc9cac9e6e29</b>_2308194320'

In [89]:
regexfile = open("rejson.txt", "w+")

In [90]:
regexfile.write("master_guid': '233880bb4c50d247f84edc9cac9e6e29_2308194320")

58

In [92]:
regexfile = open("rejson.txt")
a = regexfile.read()
print(a)

master_guid': '233880bb4c50d247f84edc9cac9e6e29_2308194320


In [99]:
import re
match = re.search(r'master_guid.*?(\w+_)', a)
print(match)
# не получается убрать символ _

<re.Match object; span=(0, 48), match="master_guid': '233880bb4c50d247f84edc9cac9e6e29_">


# Pandas

* Pandas в картинках

https://jalammar.github.io/gentle-visual-intro-to-data-analysis-python-pandas/

* 10 minutes to pandas

https://pandas.pydata.org/pandas-docs/stable/getting_started/10min.html

* 🐼реально классный твиттер чувака с крутыми pandas tricks:
    
https://mobile.twitter.com/i/moments/1158828895547854849

<img src="gifs/inprogress.gif" width="400">